### ISSUE TITLE
Wordpress.com Business Plan Limit Certain Plugin and Theme

### ISSUE THREAD

**Issue by KC20cy** [glueckpress/wpistnotwp.com#4]
Due to some system anomaly, I put some wrong info in this post and I just remove them, I don't know how to delete this thread, please help me to delete it. thank you.

**Comment by glueckpress** [comment]
Issues can’t be deleted. This is as far to deletion as anyone can go, as far as I know.

**Comment by KC20cy** [comment]
OK, thank you for your time.
